# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import os
import sys

class Ui_MainWindow(object):
    def setupUi(self, HeicConverter):
        HeicConverter.setObjectName("HeicConverter")
        HeicConverter.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(HeicConverter)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(540, 10, 240, 531))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.btn_openfolder = QtWidgets.QPushButton(self.groupBox)
        self.btn_openfolder.setGeometry(QtCore.QRect(190, 50, 41, 31))
        self.btn_openfolder.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.btn_openfolder.setTabletTracking(False)
        self.btn_openfolder.setAutoFillBackground(True)
        self.btn_openfolder.setText("")
        icon = QtGui.QIcon("img\\open-folder.png")
        self.btn_openfolder.setIcon(icon)
        self.btn_openfolder.setObjectName("btn_openfolder")
        self.imagetype = QtWidgets.QComboBox(self.groupBox)
        self.imagetype.setGeometry(QtCore.QRect(10, 100, 220, 31))
        self.imagetype.setObjectName("imagetype")
        self.imagetype.addItem("")
        self.imagetype.addItem("")
        self.btn_AddFiles = QtWidgets.QPushButton(self.groupBox)
        self.btn_AddFiles.setGeometry(QtCore.QRect(10, 330, 220, 41))
        self.btn_AddFiles.setObjectName("btn_AddFiles")
        self.btn_ClearFiles = QtWidgets.QPushButton(self.groupBox)
        self.btn_ClearFiles.setGeometry(QtCore.QRect(10, 390, 221, 51))
        self.btn_ClearFiles.setObjectName("btn_ClearFiles")
        self.btn_StartConversion = QtWidgets.QPushButton(self.groupBox)
        self.btn_StartConversion.setGeometry(QtCore.QRect(10, 480, 220, 41))
        self.btn_StartConversion.setObjectName("btn_StartConversion")
        self.btn_StartConversion.setStyleSheet("""
            QPushButton {
                background-color: #55aaff;
                color: white;
                border-radius: 5px;
                padding: 10px;
            }
            QPushButton:hover {
                background-color: #00cc66;
            }
            QPushButton:pressed {
                background-color: #808080;
            }
        """)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.targetfolder = QtWidgets.QLineEdit(self.groupBox)
        self.targetfolder.setGeometry(QtCore.QRect(10, 50, 170, 30))
        self.targetfolder.setObjectName("targetfolder")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 510, 521, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)  # Change to QListWidget
        self.listWidget.setGeometry(QtCore.QRect(5, 11, 520, 491))  # Same geometry as tableView
        self.listWidget.setObjectName("listWidget")
        
        # Add the new label at the bottom
        self.creatorLabel = QtWidgets.QLabel(self.centralwidget)
        self.creatorLabel.setGeometry(QtCore.QRect(10, 534, 780, 30))
        self.creatorLabel.setObjectName("creatorLabel")
        font = QtGui.QFont()
        font.setPointSize(9)
        self.creatorLabel.setFont(font)
        self.creatorLabel.setAlignment(QtCore.Qt.AlignCenter)
        
        HeicConverter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HeicConverter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuBuy_me_caffee = QtWidgets.QMenu(self.menubar)
        self.menuBuy_me_caffee.setObjectName("menuBuy_me_caffee")
        HeicConverter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HeicConverter)
        self.statusbar.setObjectName("statusbar")
        HeicConverter.setStatusBar(self.statusbar)
        HeicConverter.setMaximumSize(QtCore.QSize(800, 600))
        HeicConverter.setMinimumSize(QtCore.QSize(800, 600))
        self.actionOpen_Folder = QtWidgets.QAction(HeicConverter)
        self.actionOpen_Folder.setObjectName("actionOpen_Folder")
        self.actionClose = QtWidgets.QAction(HeicConverter)
        self.actionClose.setObjectName("actionClose")
        self.actionBuy_me_caffee = QtWidgets.QAction(HeicConverter)
        self.actionBuy_me_caffee.setObjectName("actionBuy_me_caffee")
        self.menuFile.addAction(self.actionOpen_Folder)
        self.menuFile.addAction(self.actionClose)
        self.menuBuy_me_caffee.addAction(self.actionBuy_me_caffee)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBuy_me_caffee.menuAction())

        self.retranslateUi(HeicConverter)
        QtCore.QMetaObject.connectSlotsByName(HeicConverter)

    def retranslateUi(self, HeicConverter):
        _translate = QtCore.QCoreApplication.translate
        HeicConverter.setWindowTitle(_translate("HeicConverter", "HeicConverter by Kadife"))
        self.groupBox.setTitle(_translate("HeicConverter", "Converter Settings"))
        self.imagetype.setItemText(0, _translate("HeicConverter", "JPEG"))
        self.imagetype.setItemText(1, _translate("HeicConverter", "PNG"))
        self.btn_AddFiles.setText(_translate("HeicConverter", "Add Files"))
        self.btn_ClearFiles.setText(_translate("HeicConverter", "Clear Files"))
        self.btn_StartConversion.setText(_translate("HeicConverter", "Start Conversion"))
        self.label.setText(_translate("HeicConverter", "Save to :"))
        self.label_2.setText(_translate("HeicConverter", "Format :"))
        self.menuFile.setTitle(_translate("HeicConverter", "File"))
        self.menuBuy_me_caffee.setTitle(_translate("HeicConverter", "Buy me caffee"))
        self.actionOpen_Folder.setText(_translate("HeicConverter", "Open Folder"))
        self.actionClose.setText(_translate("HeicConverter", "Close"))
        self.actionBuy_me_caffee.setText(_translate("HeicConverter", "Buy me caffee"))
        self.creatorLabel.setText(_translate("HeicConverter", 'Creator: Kemal Y. | <a href="https://github.com/loydi">GitHub Profile</a>'))
        self.creatorLabel.setOpenExternalLinks(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
